
# The proposed main layer implements one of the variants of home row modifers:
# - `overloadi` prevents modifiers to misfire when typing at speed.
# - `timeout` allows us to retain the repeat function of the key.
# - `overloadt2` ensures the modifier will trigger only if another key is pressed *and* released while held.

[ids]

*

[global]

oneshot_timeout = 500

[main]

shift = oneshot(shift)
meta = oneshot(meta)
control = oneshot(control)
leftalt = oneshot(alt)
rightalt = oneshot(altgr)

# Home row mods
a = overloadi(a, timeout(overloadt2(meta, a, 200), 500, a), 150)
s = overloadi(s, timeout(overloadt2(alt, s, 200), 500, s), 150)
d = overloadi(d, timeout(overloadt2(shift, d, 200), 500, d), 150)
f = overloadi(f, timeout(overloadt2(control, f, 200), 500, f), 150)
g = overloadi(g, timeout(overloadt2(altgr, g, 200), 500, g), 150)

h = overloadi(g, timeout(overloadt2(altgr, h, 200), 500, h), 150)
j = overloadi(j, timeout(overloadt2(control, j, 200), 500, j), 150)
k = overloadi(k, timeout(overloadt2(shift, k, 200), 500, k), 150)
l = overloadi(l, timeout(overloadt2(alt, l, 200), 500, l), 150)
semicolon = overloadi(semicolon, timeout(overloadt2(meta, semicolon, 200), 500, semicolon), 150)

# Chords
w+e = esc
i+o = backspace
c+v = tab
n+m= enter

# Extend layer
space = overloadi(space, timeout(overloadt2(extend, space, 200), 500, space), 125)

[extend]

q = G-5
w = G-4
e = 5
r = 102nd
t = S-.
y = G-8
p = G--
o = G-=
i = -
u = S-102nd
a = =
s = S-=
d = 6
h = left
j = down
k = up
l = right
