
# The proposed main layer implements one of the variants of home row modifers:
# - `overloadi` prevents modifiers to misfire when typing at speed.
# - `timeout` allows us to retain the repeat function of the key.
# - `overloadt2` ensures the modifier will trigger only if another key is pressed *and* released while held.

[ids]

*

[global]

oneshot_timeout = 500

[main]

shift = oneshot(shift)
meta = oneshot(meta)
control = oneshot(control)
leftalt = oneshot(alt)
rightalt = oneshot(altgr)

# Home row mods
a = overloadi(a, timeout(overloadt2(meta, a, 200), 500, a), 150)
s = overloadi(s, timeout(overloadt2(alt, s, 200), 500, s), 150)
d = overloadi(d, timeout(overloadt2(shift, d, 200), 500, d), 150)
f = overloadi(f, timeout(overloadt2(control, f, 200), 500, f), 150)
g = overloadi(g, timeout(overloadt2(altgr, g, 200), 500, g), 150)

h = overloadi(g, timeout(overloadt2(altgr, h, 200), 500, h), 150)
j = overloadi(j, timeout(overloadt2(control, j, 200), 500, j), 150)
k = overloadi(k, timeout(overloadt2(shift, k, 200), 500, k), 150)
l = overloadi(l, timeout(overloadt2(alt, l, 200), 500, l), 150)
semicolon = overloadi(semicolon, timeout(overloadt2(meta, semicolon, 200), 500, semicolon), 150)

# Chords
w+e = esc
i+o = backspace
x+c = tab
m+comma = enter

# Extend layer
space = overloadi(space, timeout(overloadt2(extend, space, 200), 500, space), 125)

[extend]

e = swap(shift)
r = swap(fumbol)
y = insert
u = home
i = up
o = end
p = pageup
a = layer(meta)
s = layer(alt)
d = layer(shift)
f = layer(control)
g = compose
h = escape
j = left
k = down
l = right
semicolon = pagedown
z = mute
x = volumedown
c = volumeup
v = playpause
n = tab
m = backspace
comma = space
dot = delete
slash = enter
